name: 'Fetch Bing Image'

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'json/**'
      - 'images/**'
  schedule:
    - cron: '30 6 * * *'
  watch:
    types: [started]

env:
  TZ: America/Montreal

jobs:
  Bing-Spider:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: 'Install dependencies'
        run: python -m pip install --upgrade pip
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt
      - name: 'Working'
        timeout-minutes: 350
        run: |
          echo `date +"%Y-%m-%d %H:%M:%S"` > time.log
          python spider.py
      - name: 'Purge CDN'
        run: curl https://purge.jsdelivr.net/gh/k-rol/DailyBingImageAPI@latest/images/latest.png
      - name: Commit files
        run: |
          git config --local user.email ${{ secrets.GIT_EMAIL }}
          git config --local user.name "Carol"
          git add -A
          git commit -m ":rocket: Fetch BingImage at $(date +'%Y-%m-%d %H:%M')" -a
      - name: 'Push changes'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          force: true
